export enum PresenterType {
  Accessibility = <any>'Accessibility',
  Assigned = <any>'Assigned',
  CollapsibleText = <any>'CollapsibleText',
  ColorBox = <any>'ColorBox',
  Completeness = <any>'Completeness',
  Craftsmanship = <any>'Craftsmanship',
  HighImpactBugs = <any>'HighImpactBugs',
  CustomerFeedback = <any>'CustomerFeedback',
  MeasurableOutcomeMet = <any>'MeasurableOutcomeMet',
  OverallGrade = <any>'OverallGrade',
  RiskAssessment = <any>'RiskAssessment',
  ScenarioValidation = <any>'ScenarioValidation',
  Shortname = <any>'Shortname',
  State = <any>'State',
  Telemetry = <any>'Telemetry',
  Text = <any>'Text',
  WorkitemLink = <any>'WorkitemLink',

  PlanningDevDesign = <any>'PlanningDevDesign',
  PlanningFuncSpec = <any>'PlanningFuncSpec',
  PlanningCompliance = <any>'PlanningCompliance',
  PlanningRisk = <any>'PlanningRisk',
  PlanningState = <any>'PlanningState',
}